configuration:
- Release
before_build:
- cmd: >-
    git clone https://github.com/SFML/SFML.git

    cd SFML

    mkdir install

    mkdir build

    cd build

    cmake -DCMAKE_INSTALL_PREFIX=../install -DBUILD_SHARED_LIBS=FALSE -DSFML_USE_STATIC_STD_LIBS=TRUE ..

    msbuild INSTALL.vcxproj

    cd ../../

    git clone https://github.com/MariaSoloveva/rep2.git SmallGameEngine
    cd SmallGameEngine
    mkdir SmallGameEngine
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=../SmallGameEngine -DSMALLGAMEENGINE_STATIC_STD_LIBS=TRUE -DSFML_STATIC_LIBS=TRUE -DCMAKE_MODULE_PATH=C:/projects/smallgameengine/SFML/install/cmake/Modules -DSFML_ROOT=C:/projects/smallgameengine/SFML/install ..
build:
  project: SmallGameEngine/build/INSTALL.vcxproj
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    cd ../../
    7z a SmallGameEngine-Windows.zip C:/projects/smallgameengine/SmallGameEngine/SmallGameEngine/ -r
artifacts:
- path: SmallGameEngine-Windows.zip
  name: SmallGameEngine-Windows
deploy:
  release: SmallGameEngine
  description: 'SmallGameEngine master branch release'
  provider: GitHub
  artifact: SmallGameEngine-windows.zip
  auth_token:
    secure: Pf37BCPu6ikFu98Rs0MDhDXzI995HHk0p0J5gPV8iy+3E20Vbdp1G6c9qVruQ0hn
  on:
    tags: true
